# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea4406a306dc7d2233d589b132d9b3c42275b8f26964f1c55a2bfe6d334a2568551a78af76653c08d6471ca0b79d65d67e441abc978166dea22841d4db1b25a

test:
  secret_key_base: e60a6f8ee230fa22c13eaed37d787f5befc9ed97c96b6555f662183f75e36017771bb2b7b24026486ca0faef0adf6b752ff28120c658abaca0c59359f62082a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
